Repository AY1920S2-CS2103T-W12-1/main, pull requests merged in 2020-02, with the labels that each got.

#61 Add Codacy badge
  README.adoc
Labels: type.Task

#65 DeveloperGuide.adoc: Write must haves for user stories
  docs/DeveloperGuide.adoc
Labels: type.DG

#71 Add profile picture, update AboutUs.adoc and ContactUs.adoc
  docs/AboutUs.adoc
  docs/ContactUs.adoc
  docs/images/exeexe93.png
  docs/team/engxuanen.adoc
Labels: priority.High, type.Task

#76 DeveloperGuide.adoc: Add Use Cases 1 to 6
  docs/AboutUs.adoc
  docs/DeveloperGuide.adoc
  docs/images/khsc96.png
  docs/images/m133225.jpg
  docs/team/khsc96.adoc
Labels: priority.High, type.DG

#79 DeveloperGuide.adoc: Add Use Cases 7 - 13
  docs/DeveloperGuide.adoc
Labels: priority.High, type.DG

#80 ContactUs.adoc: Add Kenny email
  docs/ContactUs.adoc
Labels: type.Task

#69 AboutUs.adoc: Add info for Jeremy
  docs/AboutUs.adoc
  docs/images/jeremyloh.png
  docs/team/jeremyloh.adoc
Labels: priority.High, type.Task

#84 AboutUs.adoc: Add for Amos
  docs/AboutUs.adoc
  docs/images/amoscheong97.png
  docs/team/amoscheong97.adoc
Labels: priority.High, type.Task

#81 DeveloperGuide.adoc : Added Instructions Manual Testing
  docs/DeveloperGuide.adoc
Labels: priority.High, type.DG

#85 Include new Ui image in png format
  docs/images/Ui.png
Labels: type.Task

#88 Add FriendlyMail for Wei Jie
  docs/ContactUs.adoc
Labels: type.Task

#82 DeveloperGuide.adoc: Add Glossary terms
  docs/DeveloperGuide.adoc
Labels: priority.High, type.DG

#89 Add non-functional requirements (NFR) in DG
  docs/DeveloperGuide.adoc
Labels: type.DG

#87 Add new command, Import, to User Guide.
  docs/UserGuide.adoc
Labels: priority.High, type.UG

#91 UserGuide.adoc: Update Edit feature
  docs/UserGuide.adoc
  docs/images/damithc.jpg
  docs/images/lejolly.jpg
  docs/images/yijinl.jpg
  docs/images/yl_coder.jpg
  docs/team/johndoe.adoc
Labels: priority.High, type.UG

#90 Contact us amos
  docs/ContactUs.adoc
Labels: priority.High, type.Task

#119 Remove the AB1, AB2 and AB4 navigation tabs and change AB3 to Delino.
  docs/templates/_header.html.slim
Labels: priority.High, type.Task

#92 Update titles of .adoc files to Delino
  README.adoc
  docs/DevOps.adoc
  docs/DeveloperGuide.adoc
  docs/Documentation.adoc
  docs/SettingUp.adoc
  docs/Testing.adoc
  docs/UserGuide.adoc
Labels: type.Task
