Repository AY1920S2-CS2103T-W12-1/main, pull requests merged in 2020-03, with the labels that each got.

#115 Update clear feature in User Guide.
  docs/UserGuide.adoc
Labels: priority.High, type.UG

#123 Developer Guide: Add underline for the use of list use case in delete use case.
  docs/DeveloperGuide.adoc
Labels: type.DG

#120 Update the exit and saving features in User Guide.
  docs/UserGuide.adoc
Labels: priority.High, type.UG

#121 Update User Guide (Undo, Sort, Delete Commands)
  docs/UserGuide.adoc
Labels: priority.High, type.UG

#129 Update the command summary in User Guide.
  docs/UserGuide.adoc
Labels: priority.High, type.UG

#134 Update UG features: Done and List
  docs/UserGuide.adoc
Labels: priority.High, type.UG

#114 DeveloperGuide.adoc: Update Product Scope
  docs/DeveloperGuide.adoc
Labels: priority.High, type.DG

#118 Standardise the import feature format and structure in User Guide
  docs/UserGuide.adoc
Labels: priority.High, type.UG

#116 Dg update manual testing
  docs/DeveloperGuide.adoc
Labels: priority.High, type.DG

#113 UserGuide.adoc: Update introduction section
  docs/UserGuide.adoc
Labels: severity.High, type.UG

#128 UserGuide.adoc: Update Quick start and Find
  README.adoc
  docs/LearningOutcomes.adoc
  docs/UserGuide.adoc
Labels: priority.High, type.UG

#122 Update User Guide Add command
  docs/UserGuide.adoc
Labels: priority.High, type.UG

#86 Add return feature in the UG
  docs/UserGuide.adoc
Labels: type.UG

#137 Add acknowledgement to the original source of the code
  README.adoc
Labels: priority.High

#126 README.adoc: Add brief introduction for Delino
  README.adoc
  build.gradle
  src/main/java/seedu/address/logic/commands/Command.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
Labels: type.Task

#135 UserGuide.adoc: Add appendix for glossary
  docs/UserGuide.adoc
  docs/templates/_header.html.slim
Labels: type.UG

#159 UserGuide.adoc: Add feature for v2.0
  docs/UserGuide.adoc
Labels: type.UG

#139 Update ModelClassDiagram class/interface names and related test classes
  docs/UserGuide.adoc
  docs/diagrams/ModelClassDiagram.puml
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/ClearCommand.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/OrderParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/OrderBook.java
  src/main/java/seedu/address/model/ReadOnlyAddressBook.java
  src/main/java/seedu/address/model/ReadOnlyOrderBook.java
  src/main/java/seedu/address/model/person/NameContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/person/Order.java
  src/main/java/seedu/address/model/person/UniqueOrderList.java
  src/main/java/seedu/address/model/person/UniquePersonList.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/AddressBookStorage.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/storage/JsonAddressBookStorage.java
  src/main/java/seedu/address/storage/JsonSerializableAddressBook.java
  src/main/java/seedu/address/storage/Storage.java
  src/main/java/seedu/address/storage/StorageManager.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/java/seedu/address/ui/PersonListPanel.java
  src/main/resources/view/MainWindow.fxml
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/AddCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/ClearCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/EditOrderDescriptorTest.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/OrderParserTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/model/OrderBookTest.java
  src/test/java/seedu/address/model/person/NameContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/person/OrderTest.java
  src/test/java/seedu/address/model/person/UniqueOrderListTest.java
  src/test/java/seedu/address/model/person/UniquePersonListTest.java
  src/test/java/seedu/address/storage/JsonAdaptedOrderTest.java
  src/test/java/seedu/address/storage/JsonAddressBookStorageTest.java
  src/test/java/seedu/address/storage/JsonSerializableAddressBookTest.java
  src/test/java/seedu/address/storage/StorageManagerTest.java
  src/test/java/seedu/address/testutil/AddressBookBuilder.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/address/testutil/OrderBookBuilder.java
  src/test/java/seedu/address/testutil/OrderBuilder.java
  src/test/java/seedu/address/testutil/PersonUtil.java
  src/test/java/seedu/address/testutil/TestUtil.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: priority.High, refactoring, status.Ongoing

#171 Update UG and DG: Change Add Command to Insert Command
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
Labels: priority.High, status.Ongoing, type.DG, type.Task, type.UG

#168 UserGuide and DeveloperGuide: Modify Sort command to Nearby command
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
Labels: priority.High, type.DG, type.Task, type.UG

#174 Add Warehouse field, Rename person package to order package
  docs/diagrams/LogicClassDiagram.puml
  docs/diagrams/ModelClassDiagram.puml
  docs/diagrams/tracing/LogicSequenceDiagram.puml
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/OrderBookParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/order/Address.java
  src/main/java/seedu/address/model/order/Order.java
  src/main/java/seedu/address/model/order/Warehouse.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/storage/JsonSerializableAddressBook.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/PersonListCard.fxml
  src/test/data/JsonAddressBookStorageTest/invalidAndValidPersonAddressBook.json
  src/test/data/JsonAddressBookStorageTest/invalidPersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/invalidPersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/AddCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/ClearCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/EditOrderDescriptorTest.java
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
  src/test/java/seedu/address/logic/commands/ListCommandTest.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/logic/parser/OrderBookParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/model/OrderBookTest.java
  src/test/java/seedu/address/model/order/OrderTest.java
  src/test/java/seedu/address/model/order/UniqueOrderListTest.java
  src/test/java/seedu/address/model/order/WarehouseTest.java
  src/test/java/seedu/address/storage/JsonAdaptedOrderTest.java
  src/test/java/seedu/address/storage/JsonAddressBookStorageTest.java
  src/test/java/seedu/address/storage/JsonSerializableAddressBookTest.java
  src/test/java/seedu/address/storage/StorageManagerTest.java
  src/test/java/seedu/address/testutil/EditOrderDescriptorBuilder.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/address/testutil/OrderBuilder.java
  src/test/java/seedu/address/testutil/PersonUtil.java
  src/test/java/seedu/address/testutil/TypicalOrders.java
Labels: priority.High, status.Ongoing

#173 UserGuide.adoc: Add data format for csv file to be import.
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
Labels: priority.High, type.UG

#179 Correct the bug found in isValidTimeStamp method
  src/main/java/seedu/address/model/order/TimeStamp.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/order/TimeStampTest.java
Labels: priority.High, severity.High, status.Ongoing, type.Bug

#182 Insert Command (90% done, will implement another one in the future)
  docs/diagrams/BetterModelClassDiagram.puml
  docs/diagrams/ModelClassDiagram.puml
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/itemtype/TypeOfItem.java
  src/main/java/seedu/address/model/order/CashOnDelivery.java
  src/main/java/seedu/address/model/order/Email.java
  src/main/java/seedu/address/model/order/Order.java
  src/main/java/seedu/address/model/order/TransactionID.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedOrder.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/PersonListCard.fxml
  src/test/data/JsonOrderBookStorageTest/invalidAndValidOrderAddressBook.json
  src/test/data/JsonOrderBookStorageTest/invalidOrderAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/duplicateOrderAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/invalidOrderAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalOrdersAddressBook.json
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditOrderDescriptorTest.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/order/CashOnDeliveryTest.java
  src/test/java/seedu/address/model/order/EmailTest.java
  src/test/java/seedu/address/model/order/NameContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/order/OrderTest.java
  src/test/java/seedu/address/model/order/TransactionIDTest.java
  src/test/java/seedu/address/storage/JsonAdaptedOrderTest.java
  src/test/java/seedu/address/testutil/EditOrderDescriptorBuilder.java
  src/test/java/seedu/address/testutil/OrderBuilder.java
  src/test/java/seedu/address/testutil/OrderUtil.java
  src/test/java/seedu/address/testutil/TypicalOrders.java
Labels: priority.High, refactoring, type.Epic, type.Task

#178 DeveloperGuide.adoc: Change find to search
  docs/DeveloperGuide.adoc
Labels: priority.High, status.Ongoing, type.DG

#184 Revert "Insert Command (90% done, will implement another one in the future)"
  docs/diagrams/BetterModelClassDiagram.puml
  docs/diagrams/ModelClassDiagram.puml
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/itemtype/TypeOfItem.java
  src/main/java/seedu/address/model/order/CashOnDelivery.java
  src/main/java/seedu/address/model/order/Email.java
  src/main/java/seedu/address/model/order/Order.java
  src/main/java/seedu/address/model/order/TransactionID.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedOrder.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/PersonListCard.fxml
  src/test/data/JsonOrderBookStorageTest/invalidAndValidOrderAddressBook.json
  src/test/data/JsonOrderBookStorageTest/invalidOrderAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/duplicateOrderAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/invalidOrderAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalOrdersAddressBook.json
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditOrderDescriptorTest.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/order/CashOnDeliveryTest.java
  src/test/java/seedu/address/model/order/EmailTest.java
  src/test/java/seedu/address/model/order/NameContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/order/OrderTest.java
  src/test/java/seedu/address/model/order/TransactionIDTest.java
  src/test/java/seedu/address/storage/JsonAdaptedOrderTest.java
  src/test/java/seedu/address/testutil/EditOrderDescriptorBuilder.java
  src/test/java/seedu/address/testutil/OrderBuilder.java
  src/test/java/seedu/address/testutil/OrderUtil.java
  src/test/java/seedu/address/testutil/TypicalOrders.java
Labels: priority.High

#183 Remove payment method from return command in UG/DG
  docs/UserGuide.adoc
Labels: priority.High, type.DG, type.UG

#177 UserGuide.adoc: Changed find to search
  docs/UserGuide.adoc
Labels: priority.High, status.Ongoing, type.UG

#180 Update clear command
  docs/DeveloperGuide.adoc
  docs/diagrams/LogicClassDiagram.puml
  docs/images/LogicClassDiagram.png
  docs/tutorials/AddRemark.adoc
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/ClearCommand.java
  src/main/java/seedu/address/logic/commands/CommandResult.java
  src/main/java/seedu/address/logic/commands/ExitCommand.java
  src/main/java/seedu/address/logic/commands/HelpCommand.java
  src/main/java/seedu/address/logic/parser/ClearCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/Flag.java
  src/main/java/seedu/address/logic/parser/OrderBookParser.java
  src/main/java/seedu/address/ui/ClearWindow.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/OrderCard.java
  src/main/java/seedu/address/ui/OrderListPanel.java
  src/main/resources/images/warning_icon.png
  src/main/resources/view/ClearWindow.fxml
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/OrderListCard.fxml
  src/main/resources/view/OrderListPanel.fxml
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/ClearCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandResultTest.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/ExitCommandTest.java
  src/test/java/seedu/address/logic/commands/HelpCommandTest.java
  src/test/java/seedu/address/logic/parser/ClearCommandParserTest.java
  src/test/java/seedu/address/logic/parser/FlagTest.java
  src/test/java/seedu/address/logic/parser/OrderBookParserTest.java
  src/test/java/seedu/address/model/comment/CommentTest.java
Labels: priority.High, type.DG

#181 Add Nearby command
  build.gradle
  docs/UserGuide.adoc
  docs/diagrams/NearbySequenceDiagram.puml
  src/main/java/seedu/address/logic/commands/NearbyCommand.java
  src/main/java/seedu/address/logic/commands/NearbyCommandUtil.java
  src/main/java/seedu/address/logic/parser/NearbyCommandParser.java
  src/main/java/seedu/address/logic/parser/OrderBookParser.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/test/data/JsonSerializableAddressBookTest/typicalOrdersAddressBook.json
  src/test/java/seedu/address/logic/commands/NearbyCommandTest.java
  src/test/java/seedu/address/logic/commands/NearbyCommandUtilTest.java
  src/test/java/seedu/address/logic/parser/NearbyCommandParserTest.java
  src/test/java/seedu/address/logic/parser/OrderBookParserTest.java
  src/test/java/seedu/address/testutil/TypicalOrders.java
Labels: priority.High

#185 Adapt Help Command and its relevant FXML display
  src/main/java/seedu/address/logic/commands/HelpCommand.java
  src/main/java/seedu/address/ui/HelpWindow.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/resources/view/HelpWindow.fxml
  src/main/resources/view/MainWindow.fxml
Labels: priority.High, status.Ongoing

#189 Insert_Command
  docs/DeveloperGuide.adoc
  docs/diagrams/BetterModelClassDiagram.puml
  docs/diagrams/ModelClassDiagram.puml
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/itemtype/TypeOfItem.java
  src/main/java/seedu/address/model/order/CashOnDelivery.java
  src/main/java/seedu/address/model/order/Email.java
  src/main/java/seedu/address/model/order/Order.java
  src/main/java/seedu/address/model/order/TransactionId.java
  src/main/java/seedu/address/model/tag/Tag.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedOrder.java
  src/main/java/seedu/address/storage/JsonAdaptedTag.java
  src/main/java/seedu/address/ui/OrderCard.java
  src/main/resources/view/OrderListCard.fxml
  src/test/data/JsonOrderBookStorageTest/invalidAndValidOrderAddressBook.json
  src/test/data/JsonOrderBookStorageTest/invalidOrderAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/duplicateOrderAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/invalidOrderAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalOrdersAddressBook.json
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/EditOrderDescriptorTest.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/OrderBookTest.java
  src/test/java/seedu/address/model/itemtype/TypeOfItemTest.java
  src/test/java/seedu/address/model/order/CashOnDeliveryTest.java
  src/test/java/seedu/address/model/order/EmailTest.java
  src/test/java/seedu/address/model/order/NameContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/order/OrderTest.java
  src/test/java/seedu/address/model/order/TransactionIdTest.java
  src/test/java/seedu/address/model/order/UniqueOrderListTest.java
  src/test/java/seedu/address/model/tag/TagTest.java
  src/test/java/seedu/address/storage/JsonAdaptedOrderTest.java
  src/test/java/seedu/address/testutil/EditOrderDescriptorBuilder.java
  src/test/java/seedu/address/testutil/OrderBuilder.java
  src/test/java/seedu/address/testutil/OrderUtil.java
  src/test/java/seedu/address/testutil/TypicalOrders.java
Labels: priority.High, refactoring, type.Task

#192 Modify UI elements
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/MainWindow.fxml
Labels: UI, priority.High

#187 SearchCommand: Improve on search functionality
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/commands/SearchCommand.java
  src/main/java/seedu/address/logic/parser/ArgumentMultimap.java
  src/main/java/seedu/address/logic/parser/FindCommandParser.java
  src/main/java/seedu/address/logic/parser/OrderBookParser.java
  src/main/java/seedu/address/logic/parser/SearchCommandParser.java
  src/main/java/seedu/address/model/order/KeywordContainsOrderPrefix.java
  src/main/java/seedu/address/model/order/NameContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/order/OrderContainsKeywordsPredicate.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/resources/view/MainWindow.fxml
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/SearchCommandTest.java
  src/test/java/seedu/address/logic/parser/FindCommandParserTest.java
  src/test/java/seedu/address/logic/parser/OrderBookParserTest.java
  src/test/java/seedu/address/logic/parser/SearchCommandParserTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/model/order/NameContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/order/OrderContainsKeywordsPredicateTest.java
Labels: priority.High, status.Ongoing, type.Task

#191 Edit insert feature
  docs/DeveloperGuide.adoc
  docs/diagrams/BetterModelClassDiagram.puml
  docs/diagrams/StorageClassDiagram.puml
  docs/images/BetterModelClassDiagram.png
  docs/images/ModelClassDiagram.png
  docs/images/StorageClassDiagram.png
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/InsertCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/OrderBookParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/itemtype/TypeOfItem.java
  src/main/java/seedu/address/storage/JsonAdaptedOrder.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/OrderListCard.fxml
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/InsertCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/InsertCommandTest.java
  src/test/java/seedu/address/logic/parser/InsertCommandParserTest.java
  src/test/java/seedu/address/logic/parser/OrderBookParserTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/model/itemtype/TypeOfItemTest.java
  src/test/java/seedu/address/testutil/OrderUtil.java
Labels: priority.High, status.Ongoing

#194 Nearby Command: Obtain orders from specified region of Singapore (5 general regions)
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/diagrams/NearbyClassDiagram.puml
  docs/diagrams/NearbyCommandSequenceDiagram1.puml
  docs/diagrams/NearbyCommandSequenceDiagram2.puml
  docs/images/NearbyClassDiagram.svg
  docs/images/NearbyCommandSequenceDiagram1.svg
  docs/images/NearbyCommandSequenceDiagram2.svg
  src/main/java/seedu/address/logic/commands/DistrictInfo.java
  src/main/java/seedu/address/logic/commands/NearbyCommand.java
  src/main/java/seedu/address/logic/commands/NearbyCommandUtil.java
  src/main/java/seedu/address/logic/parser/NearbyCommandParser.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/test/data/JsonSerializableAddressBookTest/typicalOrdersAddressBook.json
  src/test/java/seedu/address/logic/commands/DistrictInfoTest.java
  src/test/java/seedu/address/logic/commands/NearbyCommandTest.java
  src/test/java/seedu/address/logic/parser/NearbyCommandParserTest.java
  src/test/java/seedu/address/logic/parser/OrderBookParserTest.java
  src/test/java/seedu/address/testutil/TypicalOrders.java
Labels: priority.High, type.DG, type.Enhancement, type.UG

#198 Add check for timestamp
  src/main/java/seedu/address/model/order/TimeStamp.java
  src/test/data/JsonOrderBookStorageTest/invalidAndValidOrderBook.json
  src/test/data/JsonOrderBookStorageTest/invalidOrderDeliveryOrderBook.json
  src/test/data/JsonReturnOrderBookStorageTest/invalidAndValidReturnOrderBook.json
  src/test/data/JsonReturnOrderBookStorageTest/invalidOrderReturnOrderBook.json
  src/test/data/JsonSerializableDeliveryOrderBookTest/duplicateOrderDeliveryOrderBook.json
  src/test/data/JsonSerializableDeliveryOrderBookTest/invalidOrderDeliveryOrderBook.json
  src/test/data/JsonSerializableDeliveryOrderBookTest/typicalOrdersDeliveryOrderBook.json
  src/test/data/JsonSerializableReturnOrderBookTest/duplicateOrderReturnOrderBook.json
  src/test/data/JsonSerializableReturnOrderBookTest/invalidOrderReturnOrderBook.json
  src/test/data/JsonSerializableReturnOrderBookTest/typicalOrdersReturnOrderBook.json
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/order/OrderContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/order/TimeStampTest.java
  src/test/java/seedu/address/testutil/OrderBuilder.java
  src/test/java/seedu/address/testutil/TypicalOrders.java
Labels: priority.High, type.Enhancement

#197 Update the UML diagrams and DG for the implementation of Import feature.
  docs/DeveloperGuide.adoc
  docs/diagrams/ImportClassDiagram.puml
  docs/diagrams/ImportCommandSequenceDiagram.puml
  docs/diagrams/ImportCommandSequenceDiagram2.puml
  docs/images/ImportClassDiagram.png
  docs/images/ImportCommandSequenceDiagram.png
  docs/images/ImportCommandSequenceDiagram2.png
Labels: priority.High, type.DG

#195 UserGuide.adoc: Update userguide accordingly
  docs/UserGuide.adoc
  src/main/java/seedu/address/logic/parser/ArgumentMultimap.java
  src/main/java/seedu/address/logic/parser/SearchCommandParser.java
  src/main/java/seedu/address/model/order/KeywordContainsOrderPrefix.java
  src/main/java/seedu/address/model/order/OrderContainsKeywordsPredicate.java
  src/main/resources/view/OrderListPanel.fxml
  src/test/java/seedu/address/logic/parser/SearchCommandParserTest.java
  src/test/java/seedu/address/model/order/OrderContainsKeywordsPredicateTest.java
Labels: priority.Medium, status.Ongoing, type.UG

#202 Update all the links and UML diagrams for Developer Guide.
  docs/DeveloperGuide.adoc
  docs/diagrams/BetterModelClassDiagram.puml
  docs/diagrams/DeleteSequenceDiagram.puml
  docs/diagrams/UiClassDiagram.puml
  docs/images/BetterModelClassDiagram.png
  docs/images/DeleteSequenceDiagram.png
  docs/images/ImportCommandSequenceDiagram2.png
  docs/images/UiClassDiagram.png
Labels: priority.High, type.DG

#201 Update documents related to DG
  docs/SettingUp.adoc
  docs/diagrams/ArchitectureDiagram.puml
  docs/diagrams/ArchitectureSequenceDiagram.puml
  docs/images/ArchitectureDiagram.png
  docs/images/ArchitectureSequenceDiagram.png
Labels: priority.High, type.DG

#203 Update the UML diagram and images for Developer Guide for import command.
  docs/diagrams/ImportCommandSequenceDiagram2.puml
  docs/images/ImportCommandSequenceDiagram2.png
Labels: priority.High, type.DG

#204 Search Command developer guide update
  docs/DeveloperGuide.adoc
  docs/diagrams/SearchCommandClassDiagram.puml
  docs/diagrams/SearchCommandSequenceDiagram.puml
  docs/diagrams/SearchCommandSequenceDiagram2.puml
  docs/images/SearchCommandClassDiagram.svg
  docs/images/SearchCommandSequenceDiagram.svg
  docs/images/SearchCommandSequenceDiagram2.svg
  src/main/java/seedu/address/model/util/SampleDataUtil.java
Labels: priority.Medium, type.DG

#199 Show Command
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/diagrams/UiClassDiagram.puml
  docs/images/ArchitectureDiagram.png
  docs/images/ArchitectureSequenceDiagram.png
  docs/images/BetterModelClassDiagram.png
  docs/images/DeleteSequenceDiagram.png
  docs/images/ImportCommandSequenceDiagram2.png
  docs/images/UiClassDiagram.png
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/ClearCommand.java
  src/main/java/seedu/address/logic/commands/CommandResult.java
  src/main/java/seedu/address/logic/commands/ExitCommand.java
  src/main/java/seedu/address/logic/commands/HelpCommand.java
  src/main/java/seedu/address/logic/commands/ShowCommand.java
  src/main/java/seedu/address/logic/parser/InsertCommandParser.java
  src/main/java/seedu/address/logic/parser/OrderBookParser.java
  src/main/java/seedu/address/model/order/CashOnDelivery.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/ShowWindow.java
  src/main/resources/view/ShowWindow.fxml
  src/test/java/seedu/address/logic/commands/ClearCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandResultTest.java
  src/test/java/seedu/address/logic/commands/ExitCommandTest.java
  src/test/java/seedu/address/logic/commands/HelpCommandTest.java
  src/test/java/seedu/address/logic/commands/ShowCommandTest.java
  src/test/java/seedu/address/logic/parser/InsertCommandParserTest.java
Labels: priority.High, type.DG, type.Task, type.UG

#206 Update DG for Nearby Command diagrams
  docs/diagrams/NearbyClassDiagram.puml
  docs/images/ArchitectureDiagram.png
  docs/images/ArchitectureSequenceDiagram.png
  docs/images/BetterModelClassDiagram.png
  docs/images/DeleteSequenceDiagram.png
  docs/images/DoneSequenceDiagram.png
  docs/images/ImportCommandSequenceDiagram2.png
  docs/images/NearbyClassDiagram.svg
  docs/images/UiClassDiagram.png
Labels: status.Ongoing, type.DG

#208 DeveloperGuide.adoc: Try to fix images rendering issue
  docs/DeveloperGuide.adoc
  docs/images/ArchitectureDiagram.png
  docs/images/ArchitectureDiagram.svg
  docs/images/ArchitectureSequenceDiagram.png
  docs/images/ArchitectureSequenceDiagram.svg
  docs/images/DeleteSequenceDiagram.png
  docs/images/DeleteSequenceDiagram.svg
  docs/images/ImportCommandSequenceDiagram2.png
  docs/images/ImportCommandSequenceDiagram2.svg
  docs/images/UiClassDiagram.png
  docs/images/UiClassDiagram.svg
Labels: type.Bug, type.DG

#209 Ui changes
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/MainWindow.fxml
Labels: UI, priority.High

#211 UserGuide.adoc: Add navigation section
  docs/UserGuide.adoc
Labels: type.UG

#212 Implement additional return command logic and tests
  src/main/java/seedu/address/logic/commands/ReturnCommand.java
  src/main/java/seedu/address/logic/parser/ReturnCommandParser.java
  src/main/java/seedu/address/model/OrderBook.java
  src/main/java/seedu/address/model/ReadOnlyOrderBook.java
  src/main/java/seedu/address/model/order/UniqueOrderList.java
  src/main/java/seedu/address/model/order/returnorder/ReturnOrder.java
  src/main/java/seedu/address/storage/JsonAdaptedReturnOrder.java
  src/main/resources/view/ReturnOrderListCard.fxml
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/ReturnCommandTest.java
  src/test/java/seedu/address/logic/parser/ReturnCommandParserTest.java
  src/test/java/seedu/address/model/OrderBookTest.java
Labels: type.Task

#219 Edit the link which cause error 404 when select my profile page.
  docs/AboutUs.adoc
  docs/images/ImportClassDiagram.png
  docs/images/ImportCommandSequenceDiagram.png
  docs/images/LogicClassDiagram.png
  docs/images/ModelClassDiagram.png
  docs/images/StorageClassDiagram.png
  docs/team/exeexe93.adoc
  src/main/resources/images/warning_icon.png
Labels: priority.High, type.Bug

#220 Configure Repo to Provide Additional Data to RepoSense
  _reposense/config.json
Labels: type.Task

#221 UI color theme changes
  src/main/resources/view/CommandBox.fxml
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/Extensions.css
Labels: UI

#213 Nearby Command: Add support for searching return orders
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/diagrams/NearbyClassDiagram.puml
  docs/diagrams/NearbyCommandSequenceDiagram1.puml
  docs/diagrams/NearbyCommandSequenceDiagram2.puml
  docs/images/NearbyClassDiagram.svg
  docs/images/NearbyCommandSequenceDiagram1.svg
  docs/images/NearbyCommandSequenceDiagram2.svg
  src/main/java/seedu/address/logic/commands/DistrictInfo.java
  src/main/java/seedu/address/logic/commands/NearbyCommand.java
  src/main/java/seedu/address/logic/parser/NearbyCommandParser.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/test/data/JsonSerializableReturnOrderBookTest/typicalOrdersReturnOrderBook.json
  src/test/java/seedu/address/logic/commands/NearbyCommandTest.java
  src/test/java/seedu/address/logic/parser/NearbyCommandParserTest.java
  src/test/java/seedu/address/logic/parser/OrderBookParserTest.java
  src/test/java/seedu/address/testutil/TypicalReturnOrders.java
Labels: priority.High, type.DG, type.Enhancement, type.UG

#222 Implement Delivered Command to include returns
  docs/DeveloperGuide.adoc
  docs/images/DoneClassDiagram.svg~merged
  docs/images/DoneSequenceDiagram.svg~merged
  docs/images/ModelClassDiagram.png
  docs/images/ModelClassDiagram.svg
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/DeliveredCommand.java
  src/main/java/seedu/address/logic/commands/DoneCommand.java
  src/main/java/seedu/address/logic/commands/ReturnCommand.java
  src/main/java/seedu/address/logic/parser/DeliveredCommandParser.java
  src/main/java/seedu/address/logic/parser/DoneCommandParser.java
  src/main/java/seedu/address/logic/parser/OrderBookParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/ReturnOrderBook.java
  src/main/java/seedu/address/model/order/Order.java
  src/main/java/seedu/address/model/order/Parcel.java
  src/main/java/seedu/address/model/order/UniqueReturnOrderList.java
  src/main/java/seedu/address/model/order/returnorder/ReturnOrder.java
  src/main/java/seedu/address/model/order/returnorder/ReturnOrderContainsKeywordsPredicate.java
  src/main/java/seedu/address/storage/JsonAdaptedReturnOrder.java
  src/main/java/seedu/address/storage/JsonSerializableDeliveryOrderBook.java
  src/main/java/seedu/address/storage/JsonSerializableReturnOrderBook.java
  src/main/java/seedu/address/ui/OrderCard.java
  src/main/java/seedu/address/ui/ReturnOrderCard.java
  src/main/resources/view/OrderListCard.fxml
  src/main/resources/view/ReturnOrderListCard.fxml
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/DeliveredCommandTest.java
  src/test/java/seedu/address/logic/commands/DeliveredOrderDescriptorTest.java
  src/test/java/seedu/address/logic/commands/DoneCommandTest.java
  src/test/java/seedu/address/logic/commands/InsertCommandTest.java
  src/test/java/seedu/address/logic/commands/ReturnCommandTest.java
  src/test/java/seedu/address/logic/parser/DeliveredCommandParserTest.java
  src/test/java/seedu/address/logic/parser/DoneCommandParserTest.java
  src/test/java/seedu/address/storage/JsonAdaptedReturnOrderTest.java
  src/test/java/seedu/address/testutil/DeliveredOrderDescriptorBuilder.java
  src/test/java/seedu/address/testutil/ReturnOrderBuilder.java
  src/test/java/seedu/address/testutil/TypicalIndexes.java
Labels: priority.High, type.Task

#215 Add import feature into Delino.
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/diagrams/ImportClassDiagram.puml
  docs/images/ImportClassDiagram.png
  src/main/java/seedu/address/logic/commands/ImportCommand.java
  src/main/java/seedu/address/logic/commands/ListCommand.java
  src/main/java/seedu/address/logic/parser/ClearCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/ImportCommandParser.java
  src/main/java/seedu/address/logic/parser/OrderBookParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/CsvProcessor.java
  src/test/data/CsvFileTest/invalidCsvFile.csv
  src/test/data/CsvFileTest/validCsvFile.csv
  src/test/data/JsonSerializableDeliveryOrderBookTest/typicalOrdersDeliveryOrderBook.json
  src/test/data/JsonSerializableReturnOrderBookTest/typicalOrdersReturnOrderBook.json
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/ImportCommandTest.java
  src/test/java/seedu/address/logic/parser/ClearCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ImportCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ReturnCommandParserTest.java
  src/test/java/seedu/address/storage/CsvProcessorTest.java
  src/test/java/seedu/address/testutil/CsvBuilder.java
  src/test/java/seedu/address/testutil/CsvUtil.java
  src/test/java/seedu/address/testutil/TypicalOrders.java
  src/test/java/seedu/address/testutil/TypicalReturnOrders.java
Labels: priority.High, type.UG

#224 Update the user guide for the warning icon did not appear.
  docs/UserGuide.adoc
Labels: priority.High, type.UG

#225 UserGuide.adoc: Update Introduction, Command Summary and Nearby Command formatting
  .gitattributes
  docs/UserGuide.adoc
Labels: type.UG

#227 UserGuide.adoc: Update Search and Edit command
  docs/UserGuide.adoc
  docs/images/ImportClassDiagram.png
  docs/images/ImportCommandSequenceDiagram.png
Labels: priority.High, type.UG

#228 Update User Guide for List, Show and Insert Commands
  docs/UserGuide.adoc
Labels: priority.High, type.Task, type.UG

#229 Update UG after Consultation
  docs/UserGuide.adoc
  src/main/java/seedu/address/logic/commands/ReturnCommand.java
  src/main/java/seedu/address/logic/parser/DeliveredCommandParser.java
  src/main/java/seedu/address/logic/parser/ReturnCommandParser.java
  src/test/java/seedu/address/logic/commands/ReturnCommandTest.java
  src/test/java/seedu/address/logic/parser/ReturnCommandParserTest.java
Labels: type.UG

#216 Add logic behind searching in return list
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/SearchCommand.java
  src/main/java/seedu/address/logic/parser/ArgumentMultimap.java
  src/main/java/seedu/address/logic/parser/SearchCommandParser.java
  src/main/java/seedu/address/model/order/OrderContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/order/returnorder/ReturnOrderContainsKeywordsPredicate.java
  src/test/java/seedu/address/logic/parser/OrderBookParserTest.java
  src/test/java/seedu/address/logic/parser/SearchCommandParserTest.java
  src/test/java/seedu/address/model/order/OrderContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/order/returnorder/ReturnOrderContainsKeywordsPredicateTest.java
Labels: priority.High, type.Enhancement, type.Task

#233 Update Show Command (Fixed bugs)
  src/main/java/seedu/address/commons/util/ListUtil.java
  src/main/java/seedu/address/model/order/TimeStamp.java
  src/main/java/seedu/address/ui/ShowWindow.java
  src/main/resources/view/ShowWindow.fxml
  src/test/java/seedu/address/commons/util/ListUtilTest.java
Labels: priority.High, type.Bug, type.Task

#226 UserGuide.adoc: Update clear and import features.
  README.adoc
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/diagrams/ImportCommandSequenceDiagram2.puml
  docs/images/ArchitectureSequenceDiagram.svg
  docs/images/Delino.png
  docs/images/Delino.svg
  docs/images/ImportClassDiagram.png
  docs/images/ImportClassDiagram.svg
  docs/images/ImportCommandSequenceDiagram.png
  docs/images/ImportCommandSequenceDiagram.svg
  docs/images/ImportCommandSequenceDiagram2.svg
  docs/images/Ui.png
  src/main/java/seedu/address/ui/UiManager.java
  src/main/resources/images/address_book_32.png
  src/main/resources/images/delino_icon.png
  src/main/resources/view/MainWindow.fxml
  src/test/java/seedu/address/commons/util/AppUtilTest.java
Labels: priority.High, type.UG

#231 DeveloperGuide.adoc: Update UML class diagram of SearchCommand
  docs/DeveloperGuide.adoc
  docs/diagrams/SearchCommandClassDiagram.puml
  docs/images/SearchCommandClassDiagram.png
  docs/images/SearchCommandClassDiagram.svg
Labels: priority.High, status.Ongoing, type.DG

#235 Refactoring Clear Command.
  docs/DeveloperGuide.adoc
  docs/diagrams/ClearClassDiagram.puml
  docs/diagrams/ClearCommandSequenceDiagram.puml
  docs/diagrams/ClearCommandSequenceDiagram2.puml
  docs/images/ClearClassDiagram.svg
  docs/images/ClearCommandSequenceDiagram.svg
  docs/images/ClearCommandSequenceDiagram2.svg
  src/main/java/seedu/address/logic/parser/ClearCommandParser.java
  src/main/resources/view/ClearWindow.fxml
Labels: priority.High, refactoring, type.DG

#237 Add logging for Nearby Command
  src/main/java/seedu/address/logic/commands/NearbyCommand.java
  src/main/java/seedu/address/logic/parser/NearbyCommandParser.java
Labels: refactoring

#236 Refactor code for Return Command and Edit Ui for Help Command
  src/main/java/seedu/address/logic/commands/ReturnCommand.java
  src/main/java/seedu/address/model/ReadOnlyOrderBook.java
  src/main/java/seedu/address/ui/HelpWindow.java
  src/main/resources/view/HelpWindow.fxml
  src/test/java/seedu/address/model/OrderBookTest.java
Labels: UI, refactoring, type.Task

#239 List Command
  src/main/java/seedu/address/logic/commands/ListCommand.java
  src/main/java/seedu/address/logic/parser/OrderBookParser.java
  src/main/java/seedu/address/model/Model.java
  src/test/java/seedu/address/logic/commands/ListCommandTest.java
Labels: priority.High, type.Task

#232 DeveloperGuide.adoc: Update the link for all broken links and replace png with svg files.
  docs/DeveloperGuide.adoc
  docs/images/BetterModelClassDiagram.png
  docs/images/BetterModelClassDiagram.svg
  docs/images/LogicClassDiagram.png
  docs/images/LogicClassDiagram.svg
  docs/images/StorageClassDiagram.png
  docs/images/StorageClassDiagram.svg
  docs/team/exeexe93.adoc
Labels: priority.High, type.DG

#241 Add logging and refactor ImportCommand.
  docs/DeveloperGuide.adoc
  docs/diagrams/ClearClassDiagram.puml
  docs/diagrams/ClearCommandSequenceDiagram.puml
  docs/diagrams/ClearCommandSequenceDiagram2.puml
  docs/diagrams/ImportClassDiagram.puml
  docs/images/ClearClassDiagram.svg
  docs/images/ClearCommandSequenceDiagram2.svg
  docs/images/ImportClassDiagram.svg
  src/main/java/seedu/address/logic/commands/ClearCommand.java
  src/main/java/seedu/address/logic/commands/ImportCommand.java
  src/main/java/seedu/address/logic/parser/ClearCommandParser.java
  src/main/java/seedu/address/logic/parser/ImportCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/order/TimeStamp.java
  src/main/java/seedu/address/storage/CsvProcessor.java
  src/main/java/seedu/address/storage/JsonAdaptedOrder.java
  src/main/java/seedu/address/storage/JsonAdaptedReturnOrder.java
  src/main/java/seedu/address/ui/ClearWindow.java
Labels: priority.High, refactoring, type.DG

#238 Refactor code to follow SLAP and implement tests
  src/main/java/seedu/address/logic/commands/DeliveredCommand.java
  src/main/java/seedu/address/logic/commands/ReturnCommand.java
  src/main/java/seedu/address/logic/parser/DeliveredCommandParser.java
  src/main/java/seedu/address/logic/parser/ReturnCommandParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/ReturnOrderBook.java
  src/main/java/seedu/address/model/order/Order.java
  src/main/java/seedu/address/model/order/returnorder/ReturnOrder.java
  src/main/java/seedu/address/model/order/returnorder/UniqueReturnOrderList.java
  src/test/java/seedu/address/logic/commands/DeliveredCommandTest.java
  src/test/java/seedu/address/logic/commands/InsertCommandTest.java
  src/test/java/seedu/address/logic/commands/ReturnCommandTest.java
  src/test/java/seedu/address/logic/parser/OrderBookParserTest.java
  src/test/java/seedu/address/logic/parser/ReturnCommandParserTest.java
  src/test/java/seedu/address/model/order/returnorder/ReturnOrderTest.java
  src/test/java/seedu/address/model/order/returnorder/UniqueReturnOrderListTest.java
  src/test/java/seedu/address/testutil/OrderUtil.java
Labels: refactoring

#247 Solve the error of the Ui.png unable to show up on index.html.
  README.adoc
Labels: priority.High, type.Bug
