Repository AY1920S2-CS2103T-W12-1/main, pull requests merged in 2020-04, with the labels that each got.

#248 Branch search command Improve test coverage
  src/main/java/seedu/address/model/order/OrderContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/order/returnorder/ReturnOrderContainsKeywordsPredicate.java
  src/test/java/seedu/address/logic/commands/SearchCommandTest.java
  src/test/java/seedu/address/logic/parser/SearchCommandParserTest.java
Labels: priority.Medium, status.Ongoing, type.Enhancement

#250 DeveloperGuide.adoc: Update the uml diagrams for clear and import features.
  docs/DeveloperGuide.adoc
  docs/diagrams/ClearActivityDiagram.puml
  docs/diagrams/ClearClassDiagram.puml
  docs/diagrams/ClearCommandSequenceDiagram.puml
  docs/diagrams/ClearCommandSequenceDiagram2.puml
  docs/diagrams/ImportActivityDiagram.puml
  docs/diagrams/ImportClassDiagram.puml
  docs/diagrams/ImportCommandSequenceDiagram.puml
  docs/diagrams/ImportCommandSequenceDiagram2.puml
  docs/images/ClearActivityDiagram.svg
  docs/images/ClearClassDiagram.svg
  docs/images/ClearCommandSequenceDiagram.svg
  docs/images/ClearCommandSequenceDiagram2.svg
  docs/images/ImportActivityDiagram.svg
  docs/images/ImportClassDiagram.svg
  docs/images/ImportCommandSequenceDiagram.svg
  docs/images/ImportCommandSequenceDiagram2.svg
Labels: priority.High, type.DG

#249 Edit command developer guide updates
  docs/DeveloperGuide.adoc
  docs/diagrams/EditCommandClassDiagram.puml
  docs/diagrams/EditCommandSequenceDiagram.puml
  docs/diagrams/SearchCommandActivityDiagram.puml
  docs/diagrams/SearchCommandClassDiagram.puml
  docs/diagrams/SearchCommandSequenceDiagram.puml
  docs/diagrams/SearchCommandSequenceDiagram2.puml
  docs/images/EditCommandClassDiagram.png
  docs/images/EditCommandSequenceDiagram.svg
  docs/images/SearchCommandActivityDiagram.svg
  docs/images/SearchCommandClassDiagram.png
  docs/images/SearchCommandSequenceDiagram.svg
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
Labels: priority.High, status.Ongoing, type.DG

#251 DeveloperGuide.adoc: Update delete and nearby command
  docs/DeveloperGuide.adoc
  docs/diagrams/ArchitectureSequenceDiagram.puml
  docs/diagrams/DeleteActivityDiagram.puml
  docs/diagrams/DeleteClassDiagram.puml
  docs/diagrams/DeleteSequenceDiagram.puml
  docs/diagrams/DeleteSequenceDiagram2.puml
  docs/diagrams/NearbyActivityDiagram.puml
  docs/diagrams/NearbyClassDiagram.puml
  docs/diagrams/NearbyCommandSequenceDiagram1.puml
  docs/diagrams/NearbyCommandSequenceDiagram2.puml
  docs/diagrams/NearbySequenceDiagramParseException.puml
  docs/images/ArchitectureSequenceDiagram.svg
  docs/images/DeleteActivityDiagram.svg
  docs/images/DeleteClassDiagram.svg
  docs/images/DeleteSequenceDiagram.svg
  docs/images/DeleteSequenceDiagram2.svg
  docs/images/NearbyActivityDiagram.svg
  docs/images/NearbyClassDiagram.svg
  docs/images/NearbyCommandSequenceDiagram1.svg
  docs/images/NearbyCommandSequenceDiagram2.svg
  docs/images/NearbySequenceDiagramParseException.svg
Labels: status.Ongoing, type.UG

#252 Update DeveloperGuide.adoc for Insert and List Feature
  docs/DeveloperGuide.adoc
  docs/diagrams/InsertActivityDiagram.puml
  docs/diagrams/InsertClassDiagram.puml
  docs/diagrams/InsertCommandSequenceDiagram.puml
  docs/diagrams/ListActivityDiagram.puml
  docs/diagrams/ListClassDiagram.puml
  docs/diagrams/ListCommandSequenceDiagram.puml
  docs/images/InsertActivityDiagram.svg
  docs/images/InsertClassDiagram.svg
  docs/images/InsertCommandSequenceDiagram.svg
  docs/images/ListActivityDiagram.svg
  docs/images/ListClassDiagram.svg
  docs/images/ListCommandSequenceDiagram.svg
  src/main/java/seedu/address/logic/commands/ListCommand.java
Labels: priority.High, type.DG

#254 DeveloperGuide.adoc: Add missing delete feature and fix formatting for delivered subsection
  docs/DeveloperGuide.adoc
Labels: type.DG

#255 DeveloperGuide.adoc: Update both Command Prefix table and the possible command flags table.
  docs/DeveloperGuide.adoc
Labels: priority.High, type.DG

#256 Sort the orders and return orders by timestamp.
  src/main/java/seedu/address/model/ModelManager.java
Labels: priority.Medium, type.Enhancement

#257 Fix nearby command bug
  src/main/java/seedu/address/logic/commands/NearbyCommandUtil.java
  src/test/java/seedu/address/logic/commands/NearbyCommandTest.java
  src/test/java/seedu/address/logic/commands/NearbyCommandUtilTest.java
Labels: priority.High, type.Bug

#258 Update the Product Survey in Developer Guide.
  docs/DeveloperGuide.adoc
Labels: priority.High, type.DG

#259 Edit dg for activity diagram
  docs/DeveloperGuide.adoc
  docs/diagrams/EditCommandActivityDiagram.puml
  docs/images/EditCommandActivityDiagram.svg
Labels: priority.High, status.Ongoing, type.DG

#298 Solved sort bug which cause the return order book and filteredReturnOrders not in synchronize
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/parcel/returnorder/UniqueReturnOrderList.java
Labels: priority.High, type.Bug

#299 Bug in default sort of UniqueOrderList
  src/main/java/seedu/address/commons/core/LogsCenter.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/parcel/order/UniqueOrderList.java
Labels: priority.High, severity.High, type.Bug

#300 Fix documentation Bug
  docs/UserGuide.adoc
Labels: priority.High, type.UG

#301 Modify Postal Code description (UG and DG)
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  src/main/resources/view/DarkTheme.css
Labels: type.Bug, type.DG, type.UG

#302 Fix delivered command error message bug
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/DeliveredCommand.java
  src/test/java/seedu/address/logic/commands/DeliveredCommandTest.java
Labels: type.Bug

#303 Resolved bugs for Return and Delivered Command after PE Dry Run
  docs/UserGuide.adoc
  src/main/java/seedu/address/logic/commands/DeliveredCommand.java
  src/main/java/seedu/address/logic/commands/ReturnCommand.java
  src/main/java/seedu/address/logic/parser/DeliveredCommandParser.java
  src/test/java/seedu/address/logic/commands/DeliveredCommandTest.java
Labels: type.Bug, type.UG

#304 Update DeleteCommandParser error messages and parsing of flags
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/parser/DeleteCommandParser.java
  src/test/java/seedu/address/logic/parser/DeleteCommandParserTest.java
Labels: severity.High, type.Bug

#305 Fix name to only alphabets and enhance edit command message
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/model/parcel/parcelattributes/Name.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/model/parcel/order/NameTest.java
Labels: severity.Medium, status.Ongoing, type.Bug

#306 jeremyloh.adoc: Add major and minor enhancement section (4/4/2020)
  docs/team/jeremyloh.adoc
Labels: type.Task

#307 Add hashmap to print those data that has duplicate or parse error.
  src/main/java/seedu/address/commons/util/AppUtil.java
  src/main/java/seedu/address/logic/commands/ImportCommand.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/parcel/comment/Comment.java
  src/main/java/seedu/address/model/parcel/itemtype/TypeOfItem.java
  src/main/java/seedu/address/model/parcel/parcelattributes/TimeStamp.java
  src/main/java/seedu/address/storage/CsvProcessor.java
  src/main/java/seedu/address/storage/JsonAdaptedOrder.java
  src/main/java/seedu/address/storage/JsonAdaptedReturnOrder.java
  src/test/java/seedu/address/logic/commands/ImportCommandTest.java
  src/test/java/seedu/address/model/parcel/order/TimeStampTest.java
  src/test/java/seedu/address/storage/JsonAdaptedReturnOrderTest.java
  src/test/java/seedu/address/testutil/CsvUtil.java
Labels: priority.Medium, type.Enhancement

#311 Add restriction in UG for return timestamp
  docs/UserGuide.adoc
Labels: type.UG

#312 Add author tag to Edit and Search class done by me
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/SearchCommand.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/SearchCommandParser.java
  src/main/java/seedu/address/model/parcel/OrderContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/parcel/ReturnOrderContainsKeywordsPredicate.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/SearchCommandTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/logic/parser/SearchCommandParserTest.java
  src/test/java/seedu/address/model/parcel/order/OrderContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/parcel/returnorder/ReturnOrderContainsKeywordsPredicateTest.java
Labels: priority.Medium

#313 Add author information for JeremyLoh
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/DistrictInfo.java
  src/main/java/seedu/address/logic/commands/NearbyCommand.java
  src/main/java/seedu/address/logic/commands/NearbyCommandUtil.java
  src/main/java/seedu/address/logic/parser/DeleteCommandParser.java
  src/main/java/seedu/address/logic/parser/NearbyCommandParser.java
  src/main/java/seedu/address/model/parcel/parcelattributes/Warehouse.java
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/address/logic/commands/DistrictInfoTest.java
  src/test/java/seedu/address/logic/commands/NearbyCommandTest.java
  src/test/java/seedu/address/logic/commands/NearbyCommandUtilTest.java
  src/test/java/seedu/address/logic/parser/DeleteCommandParserTest.java
  src/test/java/seedu/address/logic/parser/NearbyCommandParserTest.java
  src/test/java/seedu/address/model/parcel/order/WarehouseTest.java
Labels: priority.Medium

#309 Fix Insert Feature bugs and fix the DG diagrams
  docs/DeveloperGuide.adoc
  docs/diagrams/InsertActivityDiagram.puml
  docs/diagrams/InsertClassDiagram.puml
  docs/diagrams/InsertCommandSequenceDiagram.puml
  docs/diagrams/InsertParserClassDiagram.puml
  docs/diagrams/ListActivityDiagram.puml
  docs/diagrams/ListClassDiagram.puml
  docs/images/InsertActivityDiagram.svg
  docs/images/InsertClassDiagram.svg
  docs/images/InsertCommandSequenceDiagram.svg
  docs/images/InsertParserClassDiagram.svg
  docs/images/ListActivityDiagram.svg
  docs/images/ListClassDiagram.svg
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/InsertCommand.java
  src/main/java/seedu/address/logic/parser/InsertCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/parcel/order/CashOnDelivery.java
  src/main/java/seedu/address/model/parcel/parcelattributes/Address.java
  src/main/java/seedu/address/model/parcel/parcelattributes/Phone.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/test/data/JsonSerializableDeliveryOrderBookTest/duplicateOrderDeliveryOrderBook.json
  src/test/data/JsonSerializableDeliveryOrderBookTest/typicalOrdersDeliveryOrderBook.json
  src/test/data/JsonSerializableReturnOrderBookTest/duplicateOrderReturnOrderBook.json
  src/test/data/JsonSerializableReturnOrderBookTest/typicalOrdersReturnOrderBook.json
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/parser/InsertCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/parcel/order/AddressTest.java
  src/test/java/seedu/address/model/parcel/order/OrderContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/parcel/order/PhoneTest.java
  src/test/java/seedu/address/model/parcel/returnorder/ReturnOrderContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/testutil/OrderBuilder.java
  src/test/java/seedu/address/testutil/ReturnOrderBuilder.java
  src/test/java/seedu/address/testutil/TypicalOrders.java
  src/test/java/seedu/address/testutil/TypicalReturnOrders.java
Labels: priority.High, refactoring, type.DG

#315 UserGuide and DeveloperGuide: Update both import and clear features
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/diagrams/ClearActivityDiagram.puml
  docs/diagrams/ClearCommandClassDiagram.puml
  docs/diagrams/ClearCommandParserClassDiagram.puml
  docs/diagrams/ClearCommandSequenceDiagram.puml
  docs/diagrams/ImportActivityDiagram.puml
  docs/diagrams/ImportCommandSequenceDiagram.puml
  docs/images/CSVSaveFormat.png
  docs/images/ClearActivityDiagram.svg
  docs/images/ClearClassDiagram.svg
  docs/images/ClearCommandClassDiagram.svg
  docs/images/ClearCommandParserClassDiagram.svg
  docs/images/ImportActivityDiagram.svg
  docs/images/ImportCommandSequenceDiagram.svg
  docs/images/OrderCSVFormat.png
  docs/images/ReturnCSVFormat.png
  docs/team/exeexe93.adoc
  src/main/java/seedu/address/logic/commands/ClearCommand.java
  src/main/java/seedu/address/logic/commands/ImportCommand.java
  src/main/java/seedu/address/logic/parser/ImportCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/test/java/seedu/address/logic/parser/ImportCommandParserTest.java
Labels: priority.High, type.Bug, type.DG, type.UG

#316 Add logger for Search and Edit, update edit command uml
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/diagrams/EditCommandActivityDiagram.puml
  docs/diagrams/EditCommandClassDiagram.puml
  docs/images/EditCommandActivityDiagram.svg
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/SearchCommand.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/SearchCommandParser.java
Labels: priority.Medium, type.DG, type.Task

#310 Fix Help Command bugs
  src/main/java/seedu/address/logic/commands/HelpCommand.java
  src/main/java/seedu/address/logic/parser/HelpCommandParser.java
  src/main/java/seedu/address/logic/parser/OrderBookParser.java
  src/main/java/seedu/address/ui/HelpWindow.java
  src/main/resources/view/HelpWindow.fxml
  src/test/java/seedu/address/logic/parser/HelpCommandParserTest.java
  src/test/java/seedu/address/logic/parser/OrderBookParserTest.java
Labels: priority.High, type.Bug

#317 Refactor hasOrder and hasReturnOrder to hasParcel
  src/main/java/seedu/address/logic/commands/InsertCommand.java
  src/main/java/seedu/address/logic/commands/ReturnCommand.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/OrderBook.java
  src/main/java/seedu/address/model/ReturnOrderBook.java
  src/main/java/seedu/address/model/parcel/order/UniqueOrderList.java
  src/main/java/seedu/address/model/parcel/returnorder/UniqueReturnOrderList.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/InsertCommandTest.java
  src/test/java/seedu/address/logic/parser/ReturnCommandParserTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/testutil/CsvUtil.java
  src/test/java/seedu/address/testutil/ReturnOrderBuilder.java
  src/test/java/seedu/address/testutil/TypicalReturnOrders.java
Labels: refactoring, type.Bug

#318 Show Command and major UI change
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/diagrams/UiClassDiagram.puml
  docs/images/UiClassDiagram.svg
  src/main/java/seedu/address/commons/util/ListUtil.java
  src/main/java/seedu/address/logic/commands/InsertCommand.java
  src/main/java/seedu/address/logic/commands/ListCommand.java
  src/main/java/seedu/address/logic/commands/ShowCommand.java
  src/main/java/seedu/address/logic/parser/InsertCommandParser.java
  src/main/java/seedu/address/logic/parser/OrderBookParser.java
  src/main/java/seedu/address/model/parcel/order/CashOnDelivery.java
  src/main/java/seedu/address/model/parcel/order/Order.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/OrderCard.java
  src/main/java/seedu/address/ui/ReturnOrderCard.java
  src/main/java/seedu/address/ui/ShowWindow.java
  src/main/resources/images/address.png
  src/main/resources/images/comments_icon.png
  src/main/resources/images/date.png
  src/main/resources/images/delivered.png
  src/main/resources/images/email.png
  src/main/resources/images/name.png
  src/main/resources/images/not_delivered.png
  src/main/resources/images/phone.png
  src/main/resources/images/warehouse.png
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/OrderListCard.fxml
  src/main/resources/view/ReturnOrderListCard.fxml
  src/test/java/seedu/address/commons/util/ListUtilTest.java
  src/test/java/seedu/address/logic/commands/InsertCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/InsertCommandTest.java
  src/test/java/seedu/address/logic/commands/ListCommandTest.java
  src/test/java/seedu/address/logic/commands/ShowCommandTest.java
  src/test/java/seedu/address/model/parcel/order/OrderContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/parcel/order/OrderTest.java
  src/test/java/seedu/address/testutil/CsvUtil.java
  src/test/java/seedu/address/testutil/TypicalOrders.java
Labels: UI, priority.High, refactoring, type.DG, type.Task, type.UG

#320 UserGuide.adoc: Reorder features section
  docs/UserGuide.adoc
Labels: type.UG

#325 Amos Cheong PPP
  docs/DeveloperGuide.adoc
  docs/team/amoscheong97.adoc
  src/main/java/seedu/address/logic/commands/ShowCommand.java
Labels: type.Task

#323 DeveloperGuide.adoc and SettingUp.adoc: Correct the broken links
  docs/DeveloperGuide.adoc
  docs/SettingUp.adoc
Labels: priority.High

#321 Kenny's PPP
  docs/DeveloperGuide.adoc
  docs/team/khsc96.adoc
Labels: priority.High, type.Task

#324 Update jeremyloh.adoc (PPP)
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/team/jeremyloh.adoc
Labels: priority.High, type.Task

#322 Add ownership to the various java and test files.
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/diagrams/ClearActivityDiagram.puml
  docs/diagrams/ClearCommandSequenceDiagram.puml
  docs/diagrams/ExecuteClearCommand.puml
  docs/diagrams/ExecuteImportCommand.puml
  docs/diagrams/ImportCommandSequenceDiagram.puml
  docs/images/ClearActivityDiagram.svg
  docs/images/ClearCommandSequenceDiagram.svg
  docs/images/ClearCommandSequenceDiagram2.svg
  docs/images/ExecuteClearCommand.svg
  docs/images/ExecuteImportCommand.svg
  docs/images/ImportCommandSequenceDiagram.svg
  docs/images/ImportCommandSequenceDiagram2.svg
  docs/team/exeexe93.adoc
  src/main/java/seedu/delino/MainApp.java
  src/main/java/seedu/delino/commons/core/Messages.java
  src/main/java/seedu/delino/commons/util/AppUtil.java
  src/main/java/seedu/delino/logic/Logic.java
  src/main/java/seedu/delino/logic/LogicManager.java
  src/main/java/seedu/delino/logic/commands/ClearCommand.java
  src/main/java/seedu/delino/logic/commands/ImportCommand.java
  src/main/java/seedu/delino/logic/parser/ClearCommandParser.java
  src/main/java/seedu/delino/logic/parser/Flag.java
  src/main/java/seedu/delino/logic/parser/ImportCommandParser.java
  src/main/java/seedu/delino/logic/parser/ParserUtil.java
  src/main/java/seedu/delino/model/Model.java
  src/main/java/seedu/delino/model/ModelManager.java
  src/main/java/seedu/delino/model/ReadOnlyReturnOrderBook.java
  src/main/java/seedu/delino/model/ReturnOrderBook.java
  src/main/java/seedu/delino/model/parcel/comment/Comment.java
  src/main/java/seedu/delino/model/parcel/parcelattributes/TimeStamp.java
  src/main/java/seedu/delino/storage/CsvProcessor.java
  src/main/java/seedu/delino/storage/JsonAdaptedReturnOrder.java
  src/main/java/seedu/delino/storage/JsonReturnOrderBookStorage.java
  src/main/java/seedu/delino/storage/JsonSerializableReturnOrderBook.java
  src/main/java/seedu/delino/storage/ReturnOrderBookStorage.java
  src/main/java/seedu/delino/ui/ClearWindow.java
  src/main/java/seedu/delino/ui/MainWindow.java
  src/main/resources/view/ClearWindow.fxml
  src/test/java/seedu/delino/logic/commands/ImportCommandTest.java
  src/test/java/seedu/delino/logic/commands/InsertCommandTest.java
  src/test/java/seedu/delino/logic/parser/ClearCommandParserTest.java
  src/test/java/seedu/delino/logic/parser/ImportCommandParserTest.java
  src/test/java/seedu/delino/model/parcel/comment/CommentTest.java
  src/test/java/seedu/delino/model/parcel/order/TimeStampTest.java
  src/test/java/seedu/delino/storage/CsvProcessorTest.java
  src/test/java/seedu/delino/storage/JsonReturnOrderBookStorageTest.java
  src/test/java/seedu/delino/storage/JsonSerializableReturnOrderBookTest.java
  src/test/java/seedu/delino/testutil/CsvBuilder.java
  src/test/java/seedu/delino/testutil/CsvUtil.java
  src/test/java/seedu/delino/testutil/ReturnOrderBookBuilder.java
Labels: priority.Medium, status.Ongoing, type.DG

#330 Update my PPP, make my UML PDF file etc.
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/diagrams/ShowCommandActivityDiagram.puml
  docs/diagrams/ShowCommandClassDiagram.puml
  docs/diagrams/ShowCommandSequenceDiagram.puml
  docs/images/ShowCommandActivityDiagram.svg
  docs/images/ShowCommandClassDiagram.svg
  docs/images/ShowCommandSequenceDiagram.svg
  docs/team/UMLDiagrams/[CS2103T-W12-01][Amos Cheong Jit Hon]UMLDiagrams.adoc
  docs/team/UMLDiagrams/[CS2103T-W12-01][Amos Cheong Jit Hon]UMLDiagrams.pdf
  docs/team/amoscheong97.adoc
  docs/team/amoscheong97.pdf
Labels: type.DG, type.Task, type.UG

#331 Update Wei Jie's PPP
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/diagrams/DeliveredClassDiagram.puml
  docs/diagrams/DeliveredCommandActivityDiagram.puml
  docs/diagrams/DeliveredSequenceDiagram.puml
  docs/diagrams/DeliveredSequenceDiagram2.puml
  docs/diagrams/ReturnClassDiagram.puml
  docs/diagrams/ReturnCommandActivityDiagram.puml
  docs/diagrams/ReturnSequenceDiagram1-a.puml
  docs/diagrams/ReturnSequenceDiagram1-b.puml
  docs/diagrams/ReturnSequenceDiagram2-a.puml
  docs/diagrams/ReturnSequenceDiagram2-b.puml
  docs/images/ReturnClassDiagram.png
  docs/images/ReturnCommandActivityDiagram.png
  docs/images/ReturnSequenceDiagram1_b.png
  docs/images/ReturnSequenceDiagram2_a.png
  docs/images/ReturnSequenceDiagram2_b.png
  docs/team/cherweijie.adoc
  src/main/java/seedu/delino/logic/commands/ReturnCommand.java
Labels: priority.High, type.DG, type.UG

#332 Move the java files to order and return order folders in storage folder.
  docs/diagrams/StorageClassDiagram.puml
  docs/images/StorageClassDiagram.svg
  src/main/java/seedu/delino/MainApp.java
  src/main/java/seedu/delino/storage/Storage.java
  src/main/java/seedu/delino/storage/StorageManager.java
  src/main/java/seedu/delino/storage/order/JsonAdaptedOrder.java
  src/main/java/seedu/delino/storage/order/JsonOrderBookStorage.java
  src/main/java/seedu/delino/storage/order/JsonSerializableDeliveryOrderBook.java
  src/main/java/seedu/delino/storage/order/OrderBookStorage.java
  src/main/java/seedu/delino/storage/returnorder/JsonAdaptedReturnOrder.java
  src/main/java/seedu/delino/storage/returnorder/JsonReturnOrderBookStorage.java
  src/main/java/seedu/delino/storage/returnorder/JsonSerializableReturnOrderBook.java
  src/main/java/seedu/delino/storage/returnorder/ReturnOrderBookStorage.java
  src/test/java/seedu/delino/logic/LogicManagerTest.java
  src/test/java/seedu/delino/storage/StorageManagerTest.java
  src/test/java/seedu/delino/storage/order/JsonAdaptedOrderTest.java
  src/test/java/seedu/delino/storage/order/JsonOrderBookStorageTest.java
  src/test/java/seedu/delino/storage/order/JsonSerializableDeliveryOrderBookTest.java
  src/test/java/seedu/delino/storage/returnorder/JsonAdaptedReturnOrderTest.java
  src/test/java/seedu/delino/storage/returnorder/JsonReturnOrderBookStorageTest.java
  src/test/java/seedu/delino/storage/returnorder/JsonSerializableReturnOrderBookTest.java
Labels: priority.Medium

#333 Add UML diagrams asciidoc for Jeremy
  docs/team/UMLDiagrams/[CS2103T-W12-01][Loh Jeremy Wen Jun]UML Diagrams.adoc
Labels: type.Task

#334 Include help command UML diagrams, in DG and PPP
  docs/DeveloperGuide.adoc
  docs/diagrams/HelpCommandActivityDiagram.puml
  docs/diagrams/HelpCommandClassDiagram.puml
  docs/diagrams/HelpCommandSequenceDiagram.puml
  docs/images/HelpCommandActivityDiagram.png
  docs/images/HelpCommandClassDiagram.png
  docs/images/HelpCommandSequenceDiagram.png
  docs/images/ReturnSequenceDiagram1_a.png
  docs/team/UMLDiagrams/[CS2103T-W12-01][Cher Wei Jie]UMLDiagrams.adoc
  docs/team/UMLDiagrams/[CS2103T-W12-01][Cher Wei Jie]UMLDiagrams.pdf
  docs/team/amoscheong97.pdf
  src/main/java/seedu/delino/logic/commands/ReturnCommand.java
Labels: priority.High, type.DG

#337 Refactor isSameParcel method
  src/main/java/seedu/delino/model/parcel/returnorder/ReturnOrder.java
  src/test/java/seedu/delino/logic/commands/ImportCommandTest.java
  src/test/java/seedu/delino/model/parcel/returnorder/ReturnOrderTest.java
Labels: refactoring

#338 DeveloperGuide.adoc: Update DG author and UC
  docs/DeveloperGuide.adoc
Labels: priority.High, type.DG

#336 Clock on menu bar
  README.adoc
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/images/Ui.png
  docs/team/khsc96.adoc
  docs/team/khsc96.pdf
  src/main/java/seedu/delino/ui/MainWindow.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/MainWindow.fxml
Labels: priority.High, type.Story, type.Task

#339 Update of UML diagram for Eng Xuan En.
  docs/DeveloperGuide.adoc
  docs/diagrams/ClearCommandClassDiagram.puml
  docs/diagrams/ClearCommandParserClassDiagram.puml
  docs/diagrams/ClearCommandSequenceDiagram.puml
  docs/diagrams/ImportClassDiagram.puml
  docs/images/ClearCommandClassDiagram.svg
  docs/images/ClearCommandParserClassDiagram.svg
  docs/images/ClearCommandSequenceDiagram.svg
  docs/images/ImportClassDiagram.svg
  docs/team/UMLDiagrams/[CS2103T-W12-01][Eng Xuan En]UML Diagrams.adoc
  docs/team/UMLDiagrams/[CS2103T-W12-01][Eng Xuan En]UML Diagrams.pdf
  docs/team/UMLDiagrams/[CS2103T-W12-01][Eng Xuan En]UMLDiagrams.adoc
  src/main/resources/images/warning_icon.png
Labels: priority.High

#340 Delete Command: Add message for return order list deletion
  docs/DeveloperGuide.adoc
  src/main/java/seedu/delino/logic/commands/DeleteCommand.java
  src/test/java/seedu/delino/logic/commands/DeleteCommandTest.java
Labels: severity.Low, type.Bug, type.Task

#342 Changes made to the timestamp.
  docs/UserGuide.adoc
  src/main/java/seedu/delino/logic/parser/ParserUtil.java
  src/main/java/seedu/delino/model/parcel/parcelattributes/TimeStamp.java
  src/main/java/seedu/delino/model/util/SampleDataUtil.java
  src/main/java/seedu/delino/storage/order/JsonAdaptedOrder.java
  src/main/java/seedu/delino/storage/returnorder/JsonAdaptedReturnOrder.java
  src/test/java/seedu/delino/logic/parser/ParserUtilTest.java
  src/test/java/seedu/delino/model/parcel/order/TimeStampTest.java
  src/test/java/seedu/delino/storage/returnorder/JsonAdaptedReturnOrderTest.java
  src/test/java/seedu/delino/testutil/DeliveredParcelDescriptorBuilder.java
  src/test/java/seedu/delino/testutil/EditParcelDescriptorBuilder.java
  src/test/java/seedu/delino/testutil/OrderBuilder.java
  src/test/java/seedu/delino/testutil/ReturnOrderBuilder.java
Labels: priority.Medium

#341 Add @@author information for @Cherweijie
  src/main/java/seedu/delino/logic/commands/DeliveredCommand.java
  src/main/java/seedu/delino/logic/commands/HelpCommand.java
  src/main/java/seedu/delino/logic/commands/ReturnCommand.java
  src/main/java/seedu/delino/logic/parser/DeliveredCommandParser.java
  src/main/java/seedu/delino/logic/parser/HelpCommandParser.java
  src/main/java/seedu/delino/logic/parser/ReturnCommandParser.java
  src/main/java/seedu/delino/model/parcel/returnorder/ReturnOrder.java
  src/main/java/seedu/delino/ui/HelpWindow.java
  src/main/java/seedu/delino/ui/ReturnOrderCard.java
  src/main/java/seedu/delino/ui/ReturnOrderListPanel.java
  src/test/java/seedu/delino/logic/commands/DeliveredCommandTest.java
  src/test/java/seedu/delino/logic/commands/DeliveredParcelDescriptorTest.java
  src/test/java/seedu/delino/logic/commands/HelpCommandTest.java
  src/test/java/seedu/delino/logic/commands/ReturnCommandTest.java
  src/test/java/seedu/delino/logic/parser/DeliveredCommandParserTest.java
  src/test/java/seedu/delino/logic/parser/HelpCommandParserTest.java
  src/test/java/seedu/delino/logic/parser/ReturnCommandParserTest.java
  src/test/java/seedu/delino/testutil/DeliveredParcelDescriptorBuilder.java
  src/test/java/seedu/delino/testutil/ReturnOrderBuilder.java
Labels: type.Task

#343 Refactor DelinoParser
  src/main/java/seedu/delino/logic/LogicManager.java
  src/main/java/seedu/delino/logic/parser/DelinoParser.java
  src/test/java/seedu/delino/logic/parser/DelinoParserTest.java
Labels: refactoring

#345 Update UML sequence diagram for DelinoParser
  docs/diagrams/EditCommandSequenceDiagram.puml
  docs/diagrams/SearchCommandSequenceDiagram.puml
  docs/images/EditCommandSequenceDiagram.svg
  docs/images/SearchCommandSequenceDiagram.svg
Labels: type.DG

#347 Update DG: add description to diagrams
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/diagrams/InsertActivityDiagram.puml
  docs/diagrams/InsertCommandSequenceDiagram.puml
  docs/diagrams/ListCommandSequenceDiagram.puml
  docs/diagrams/ShowCommandActivityDiagram.puml
  docs/diagrams/ShowCommandSequenceDiagram.puml
  docs/images/InsertActivityDiagram.svg
  docs/images/InsertCommandSequenceDiagram.svg
  docs/images/ListCommandSequenceDiagram.svg
  docs/images/ShowCommandActivityDiagram.svg
  docs/images/ShowCommandSequenceDiagram.svg
  src/main/java/seedu/delino/logic/commands/InsertCommand.java
  src/main/java/seedu/delino/logic/commands/ListCommand.java
  src/main/java/seedu/delino/logic/commands/ShowCommand.java
  src/main/java/seedu/delino/logic/parser/InsertCommandParser.java
  src/main/java/seedu/delino/model/parcel/order/CashOnDelivery.java
  src/main/java/seedu/delino/model/parcel/parcelattributes/Address.java
  src/main/java/seedu/delino/model/parcel/parcelattributes/Phone.java
  src/test/java/seedu/delino/logic/commands/InsertCommandIntegrationTest.java
  src/test/java/seedu/delino/logic/commands/InsertCommandTest.java
  src/test/java/seedu/delino/logic/commands/ListCommandTest.java
  src/test/java/seedu/delino/logic/commands/ShowCommandTest.java
Labels: type.DG, type.UG

#344 Update the Ui UML diagram.
  docs/diagrams/UiClassDiagram.puml
  docs/images/UiClassDiagram.svg
Labels: priority.Medium

#346 Add styling to the UML Diagrams Report.
  docs/team/UMLDiagrams/[CS2103T-W12-01][Eng Xuan En]UML Diagrams.adoc
Labels: priority.Low

#348 Update the UML diagrams due to the change in naming.
  docs/diagrams/ClearCommandSequenceDiagram.puml
  docs/diagrams/ImportCommandSequenceDiagram.puml
  docs/diagrams/StorageClassDiagram.puml
  docs/images/ClearCommandSequenceDiagram.svg
  docs/images/ImportCommandSequenceDiagram.svg
  docs/images/StorageClassDiagram.svg
  docs/team/exeexe93.pdf
  src/main/java/seedu/delino/storage/order/JsonOrderBookStorage.java
  src/main/java/seedu/delino/storage/order/JsonSerializableOrderBook.java
  src/test/data/JsonOrderBookStorageTest/invalidOrdersOrderBook.json
  src/test/data/JsonSerializableOrderBookTest/duplicateOrdersOrderBook.json
  src/test/data/JsonSerializableOrderBookTest/invalidOrderBook.json
  src/test/data/JsonSerializableOrderBookTest/typicalOrdersOrderBook.json
  src/test/java/seedu/delino/storage/order/JsonOrderBookStorageTest.java
  src/test/java/seedu/delino/storage/order/JsonSerializableOrderBookTest.java
Labels: priority.High

#349 Refactor for DelinoParser and update Model class diagrams
  docs/DeveloperGuide.adoc
  docs/diagrams/BetterModelClassDiagram.puml
  docs/diagrams/DeliveredSequenceDiagram.puml
  docs/diagrams/HelpCommandSequenceDiagram.puml
  docs/diagrams/ModelClassDiagram.puml
  docs/diagrams/ReturnSequenceDiagram1-a.puml
  docs/diagrams/ReturnSequenceDiagram1-b.puml
  docs/images/BetterModelClassDiagram.png
  docs/images/BetterModelClassDiagram.svg
  docs/images/DeliveredSequenceDiagram.png
  docs/images/DeliveredSequenceDiagram2.png
  docs/images/DoneClassDiagram.svg
  docs/images/DoneClassDiagram.svg~merged
  docs/images/DoneSequenceDiagram.svg
  docs/images/DoneSequenceDiagram.svg~merged
  docs/images/HelpCommandSequenceDiagram.png
  docs/images/ModelClassDiagram.png
  docs/images/ModelClassDiagram.svg
  docs/images/ReturnSequenceDiagram1_a.png
  docs/images/ReturnSequenceDiagram1_b.png
  src/main/java/seedu/delino/logic/commands/DeliveredCommand.java
  src/main/java/seedu/delino/logic/commands/EditCommand.java
  src/main/java/seedu/delino/logic/parser/InsertCommandParser.java
  src/main/java/seedu/delino/logic/parser/ParserUtil.java
  src/main/java/seedu/delino/logic/parser/ReturnCommandParser.java
  src/main/java/seedu/delino/model/parcel/Parcel.java
  src/main/java/seedu/delino/model/parcel/optionalparcelattributes/Comment.java
  src/main/java/seedu/delino/model/parcel/optionalparcelattributes/TypeOfItem.java
  src/main/java/seedu/delino/model/parcel/order/Order.java
  src/main/java/seedu/delino/model/parcel/returnorder/ReturnOrder.java
  src/main/java/seedu/delino/model/util/SampleDataUtil.java
  src/main/java/seedu/delino/storage/order/JsonAdaptedOrder.java
  src/main/java/seedu/delino/storage/returnorder/JsonAdaptedReturnOrder.java
  src/test/java/seedu/delino/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/delino/logic/parser/InsertCommandParserTest.java
  src/test/java/seedu/delino/logic/parser/ParserUtilTest.java
  src/test/java/seedu/delino/logic/parser/ReturnCommandParserTest.java
  src/test/java/seedu/delino/model/parcel/comment/CommentTest.java
  src/test/java/seedu/delino/model/parcel/itemtype/TypeOfItemTest.java
  src/test/java/seedu/delino/storage/order/JsonAdaptedOrderTest.java
  src/test/java/seedu/delino/storage/returnorder/JsonAdaptedReturnOrderTest.java
  src/test/java/seedu/delino/testutil/DeliveredParcelDescriptorBuilder.java
  src/test/java/seedu/delino/testutil/EditParcelDescriptorBuilder.java
  src/test/java/seedu/delino/testutil/OrderBuilder.java
  src/test/java/seedu/delino/testutil/ReturnOrderBuilder.java
Labels: refactoring, type.DG

#350 Fix the bug whereby there are extra newline for every line in the error message.
  src/main/java/seedu/delino/logic/commands/ImportCommand.java
Labels: priority.Low, type.Bug

#351 DeveloperGuide: Update format
  docs/DeveloperGuide.adoc
  docs/SettingUp.adoc
  docs/Testing.adoc
  docs/diagrams/DeleteSequenceDiagram.puml
  docs/diagrams/DeleteSequenceDiagram2.puml
  docs/diagrams/LogicClassDiagram.puml
  docs/diagrams/NearbyCommandSequenceDiagram1.puml
  docs/diagrams/NearbyCommandSequenceDiagram2.puml
  docs/diagrams/NearbySequenceDiagramParseException.puml
  docs/images/DeleteSequenceDiagram.svg
  docs/images/DeleteSequenceDiagram2.svg
  docs/images/LogicClassDiagram.svg
  docs/images/NearbyCommandSequenceDiagram1.svg
  docs/images/NearbyCommandSequenceDiagram2.svg
  docs/images/NearbySequenceDiagramParseException.svg
  src/main/java/seedu/delino/ui/MainWindow.java
  src/main/java/seedu/delino/ui/StatusBarFooter.java
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/StatusBarFooter.fxml
Labels: type.DG

#354 DeveloperGuide.adoc: Update the product scope, glossary and effort portion.
  docs/DeveloperGuide.adoc
Labels: priority.High, type.DG

#356 Change display message for return
  ReturnCommandActivityDiagram.png
  ReturnSequenceDiagram1_a.png
  src/main/java/seedu/delino/logic/commands/ReturnCommand.java
Labels: UI

#355 UC update for Edit, search and show
  docs/DeveloperGuide.adoc
Labels: type.DG, type.Task

#357 Help Window resizing and change display message
  src/main/java/seedu/delino/ui/HelpWindow.java
  src/main/resources/view/HelpWindow.fxml
Labels: UI, type.Bug

#358 Remove duplicate test file and add author acknowledgment.
  docs/diagrams/UiClassDiagram.puml
  docs/team/UMLDiagrams/[CS2103T-W12-01][Eng Xuan En]UML Diagrams.adoc
  src/main/java/seedu/delino/logic/parser/ParserUtil.java
  src/main/java/seedu/delino/ui/MainWindow.java
  src/test/java/seedu/delino/logic/commands/ClearCommandTest.java
  src/test/java/seedu/delino/model/parcel/optionalparcelattributes/CommentTest.java
  src/test/java/seedu/delino/model/parcel/optionalparcelattributes/TypeOfItemTest.java
  src/test/java/seedu/delino/model/parcel/returnorder/ReturnOrderBookTest.java
  src/test/java/seedu/delino/storage/returnorder/JsonAdaptedReturnOrderTest.java
  src/test/java/seedu/delino/testutil/TypicalReturnOrders.java
Labels: priority.Medium

#360 Add logger into files, change equals() method and rectify DG and UG
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  src/main/java/seedu/delino/logic/commands/DeliveredCommand.java
  src/main/java/seedu/delino/logic/commands/HelpCommand.java
  src/main/java/seedu/delino/logic/commands/ReturnCommand.java
  src/main/java/seedu/delino/logic/parser/DelinoParser.java
  src/main/java/seedu/delino/logic/parser/DeliveredCommandParser.java
  src/main/java/seedu/delino/logic/parser/HelpCommandParser.java
  src/main/java/seedu/delino/logic/parser/ReturnCommandParser.java
  src/main/java/seedu/delino/model/parcel/parcelattributes/TransactionId.java
  src/main/resources/view/HelpWindow.fxml
  src/test/java/seedu/delino/model/parcel/order/TransactionIdTest.java
Labels: UI, refactoring, type.DG, type.UG

#359 Change the name from return list to return order list for the Ui and update the Ui.png.
  docs/images/Ui.png
  src/main/resources/view/MainWindow.fxml
Labels: UI, priority.Low

#361 Add loggers, add test cases and update error message.
  src/main/java/seedu/delino/logic/commands/InsertCommand.java
  src/main/java/seedu/delino/logic/commands/ListCommand.java
  src/main/java/seedu/delino/logic/commands/ShowCommand.java
  src/main/java/seedu/delino/logic/parser/InsertCommandParser.java
  src/main/java/seedu/delino/logic/parser/ParserUtil.java
  src/main/java/seedu/delino/model/parcel/optionalparcelattributes/TypeOfItem.java
  src/main/java/seedu/delino/ui/MainWindow.java
  src/test/java/seedu/delino/logic/commands/CommandTestUtil.java
  src/test/java/seedu/delino/logic/parser/InsertCommandParserTest.java
Labels: priority.High, type.Task

#362 Change the error message for clear features.
  docs/DeveloperGuide.adoc
  docs/diagrams/ClearActivityDiagram.puml
  docs/diagrams/ExecuteClearCommand.puml
  docs/images/ClearActivityDiagram.svg
  docs/images/ExecuteClearCommand.svg
  src/main/java/seedu/delino/logic/commands/ClearCommand.java
  src/main/java/seedu/delino/ui/ClearWindow.java
  src/test/java/seedu/delino/logic/commands/ClearCommandTest.java
Labels: priority.Medium, type.DG

#363 Refactor search command and change width of Ui image
  build.gradle
  docs/images/Ui.png
  docs/images/address.png
  src/main/java/seedu/delino/logic/commands/SearchCommand.java
  src/main/java/seedu/delino/ui/OrderCard.java
  src/main/java/seedu/delino/ui/ReturnOrderCard.java
  src/main/resources/images/address.png
Labels: UI, priority.Medium, type.Enhancement

#364 Update PPP for Jeremy
  docs/team/UMLDiagrams/[CS2103T-W12-1][Loh Jeremy Wen Jun]UML Diagrams.adoc
  docs/team/jeremyloh.adoc
Labels: type.Task

#366 Add HTML File for Jeremy PPP
  docs/team/jeremyloh.adoc
  docs/team/jeremyloh.html
Labels: type.Task

#370 Regenerate new html file and minor changes to help.
  docs/UserGuide.adoc
  src/main/java/seedu/delino/ui/HelpWindow.java
Labels: type.Bug, type.UG

#371 Update Nearby Command to check for valid flag arguments
  src/main/java/seedu/delino/logic/commands/NearbyCommand.java
  src/main/java/seedu/delino/logic/parser/NearbyCommandParser.java
  src/test/java/seedu/delino/logic/commands/NearbyCommandTest.java
  src/test/java/seedu/delino/logic/parser/NearbyCommandParserTest.java
Labels: severity.Low, type.Bug

#372 Update PPP and its HTML File for Jeremy
  docs/stylesheets/gh-pages.css
  docs/team/jeremyloh.adoc
  docs/team/jeremyloh.html
Labels: type.Task

#373 Update the PPP and the html format of PPP for Eng Xuan En.
  docs/UserGuide.adoc
  docs/stylesheets/gh-pages.css
  docs/team/exeexe93.adoc
  docs/team/exeexe93.html
Labels: priority.High, type.UG

#374 UserGuide.adoc: Remove future features, update phone number format, update show and return command summary
  docs/UserGuide.adoc
Labels: type.Bug, type.UG

#377 Update my DG
  docs/DeveloperGuide.adoc
  docs/stylesheets/gh-pages.css
  docs/team/amoscheong97.adoc
  docs/team/amoscheong97.html
Labels: type.DG, type.Task

#378 Update DG and UG
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/team/cherweijie.html
Labels: type.DG, type.UG

#376 DeveloperGuide.adoc: Correct the errors found after generating the PDF file
  docs/DeveloperGuide.adoc
Labels: priority.High, type.Bug, type.DG

#379 Update kloc count for Delino in all PPP asciidoc
  docs/team/amoscheong97.adoc
  docs/team/cherweijie.adoc
  docs/team/exeexe93.adoc
  docs/team/jeremyloh.adoc
  docs/team/khsc96.adoc
Labels: type.Task

#380 Changes to UG to standardise cross-links
  docs/UserGuide.adoc
  docs/stylesheets/gh-pages.css
Labels: type.Bug, type.UG

#381 Fix quick start message in UG
  docs/UserGuide.adoc
  docs/team/amoscheong97.html
  docs/team/cherweijie.html
  docs/team/exeexe93.html
  docs/team/jeremyloh.html
  docs/team/khsc96.html
Labels: type.UG
